### ISSUE TITLE
shelljs breaks on windows

### ISSUE THREAD

**Issue by Gumphrie** [krzysztof-o/spritesheet.js#48]
Hi, after the pull request at https://github.com/krzysztof-o/spritesheet.js/pull/43 was accepted spritesheet-js is no longer working on Windows when specifying a long list of files as shelljs doesn't handle the Windows argument length limit for exec() like platform-cmd did...

Can we get that functionality back by maybe just including the platform-cmd code for exec() that worked?

Thanks in Advance

**Comment by krzysztof-o** [comment]
should be fixed now

**Comment by Gumphrie** [comment]
Thanks a lot for such a speedy change, I see you have reverted to platform-cmd, does that resolve also the earlier problem of platform-cmd getting confused with platform-command which I think is why we went went with shelljs or is that still an issue?

**Comment by krzysztof-o** [comment]
I don't have Windows to test on :)
If you have it then gently please test it and send PR in case it's not working :)
