### ISSUE TITLE
Uncaught exception on Windows

### ISSUE THREAD

**Issue by jimvonmoon** [krzysztof-o/spritesheet.js#60]
When running spritesheet.js on Windows I always get the following message:
```bash
> spritesheet-js -f json *.png                                                
                                                                              
C:\Users\SomeUser\AppData\Roaming\npm\node_modules\spritesheet-js\index.js:129     
    if (err) throw err;                                                       
             ^                                                                
1                                                                             
```

I tried lots of different parameters with the same result. `spritesheet-js -h` works fine. I install spritesheet.js via npm.

Some basic system info:
```
System: Windows 7 64-bit
spritesheet.js version: 1.2.6
node.js version: 6.10.0
npm version: 3.10.10
```

**Comment by digijin** [comment]
On Windows, cloned the repo and ran `mocha test` and every test failed except `should generate data file`

**Comment by seiyria** [comment]
I'm actually getting this error presumably because I have a lot of images it's concatting. Error code of 1 sadly isn't very useful since there is no accompanying stack trace. Imagemagick 7 has an option to install legacy tools so I did that, and they're available on my PATH, but I think it might be choking because it's making too large of a command.

**Comment by kyuur** [comment]
A note for anyone else who may come across this issue: although the tooling was available on my PATH and working from everywhere I could think of (cygwin in cmd, git bash, etc) it wasn't working from spritesheet.js immediately. Rebooting my PC after installation (of 6.x or 7.x w/ legacy) did the trick.
