### ISSUE TITLE
os.tmpDir() is deprecated. Use os.tmpdir() instead

### ISSUE THREAD

**Issue by axldns** [krzysztof-o/spritesheet.js#62]
https://github.com/krzysztof-o/spritesheet.js/blob/2757c39f6f17c8a09105082adae646346504fecc/lib/generator.js#L27

**Comment by axldns** [comment]
fixed in https://github.com/krzysztof-o/spritesheet.js/commit/ea90c616255ebd209939055ecebe013e6017c346

**Comment by adamsoderstrom** [comment]
This error is still occuring through npm installation.
